package ventanas;

import clases.DNI;
import clases.ListaUsuarios;
import clases.Usuario;
import excepciones.ContrasenhaCorrectaException;
import excepciones.EmailCorrectoException;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author dam117
 */
public class Vregistro extends javax.swing.JFrame {
    static Vregistro registro = new Vregistro(); //Ventana creada estática para poder usarla desde cualquier ventana

    /**
     * Creates new form Vregistro
     */
    public Vregistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLogoAddUser = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblnombreUsuario = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        lblnombre = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        lblapellidos = new javax.swing.JLabel();
        txtapellidos = new javax.swing.JTextField();
        lbldni = new javax.swing.JLabel();
        txtdni = new javax.swing.JTextField();
        lblcorreo = new javax.swing.JLabel();
        txtcorreo = new javax.swing.JTextField();
        lblcorreo2 = new javax.swing.JLabel();
        txtcorreo2 = new javax.swing.JTextField();
        lblpassword = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        lblpassword2 = new javax.swing.JLabel();
        txtpassword2 = new javax.swing.JPasswordField();
        botonEnviar = new javax.swing.JButton();
        botonBorrar = new javax.swing.JButton();
        mensajeCorreo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro");
        setIconImage(getIconImage());
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblLogoAddUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/addUser.png"))); // NOI18N

        lblTitulo.setFont(new java.awt.Font("MV Boli", 1, 48)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(204, 0, 102));
        lblTitulo.setText("Registro");

        lblnombreUsuario.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        lblnombreUsuario.setText("Nombre de usuario:");

        txtusuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 102), 2, true));

        lblnombre.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        lblnombre.setText("Nombre:");

        txtnombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 102), 2, true));

        lblapellidos.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        lblapellidos.setText("Apellidos:");

        txtapellidos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 102), 2, true));

        lbldni.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        lbldni.setText("DNI:");

        txtdni.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 102), 2, true));

        lblcorreo.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        lblcorreo.setText("email:");

        txtcorreo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 102), 2, true));

        lblcorreo2.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        lblcorreo2.setText("Repetir email:");

        txtcorreo2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 102), 2, true));
        txtcorreo2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcorreo2FocusLost(evt);
            }
        });

        lblpassword.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        lblpassword.setText("Contraseña:");

        txtpassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 102), 2, true));

        lblpassword2.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        lblpassword2.setText("Repetir contraseña:");

        txtpassword2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 102), 2, true));

        botonEnviar.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        botonEnviar.setText("Enviar");
        botonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEnviarActionPerformed(evt);
            }
        });

        botonBorrar.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        botonBorrar.setText("Borrar datos");
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });

        mensajeCorreo.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        mensajeCorreo.setForeground(new java.awt.Color(204, 0, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblnombreUsuario)
                                    .addComponent(lblnombre)
                                    .addComponent(lblapellidos)
                                    .addComponent(lbldni)
                                    .addComponent(lblcorreo)
                                    .addComponent(lblcorreo2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtnombre)
                                    .addComponent(txtapellidos)
                                    .addComponent(txtusuario, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtdni, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                    .addComponent(txtcorreo)
                                    .addComponent(txtcorreo2, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                    .addComponent(mensajeCorreo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblpassword)
                                    .addComponent(lblpassword2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtpassword)
                                    .addComponent(txtpassword2, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)))
                            .addComponent(lblLogoAddUser))
                        .addGap(33, 33, 33))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(botonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(242, 242, 242))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblnombreUsuario)
                            .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblnombre)
                            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblapellidos)
                            .addComponent(txtapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblLogoAddUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtdni)
                    .addComponent(lbldni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblcorreo)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblpassword)
                        .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcorreo2)
                    .addComponent(txtcorreo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblpassword2)
                    .addComponent(txtpassword2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mensajeCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(571, 389));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEnviarActionPerformed
        try {
            DNI midni = new DNI(txtdni.getText()); //Comprueba que el dni sea correcto y lo asigna
            if (!txtpassword.getText().equalsIgnoreCase(txtpassword2.getText())) { //Si las contraseñas introducidas no son iguales salta un mensaje
                JOptionPane.showMessageDialog(null, "Creación denegada:\n"
                        + "Las contraseñas no coinciden", "Error",
                        JOptionPane.ERROR_MESSAGE);
            } else { //Si son iguales ejecuta
                if (!(txtusuario.getText().isEmpty() && txtnombre.getText().isEmpty()
                        && txtapellidos.getText().isEmpty() && txtcorreo.getText().isEmpty()
                        && txtpassword.getText().isEmpty())) { //Si no hay ningun campo vacio crea el usuario
                    Usuario usuario = new Usuario(txtusuario.getText(), txtnombre.getText(), txtapellidos.getText(), txtcorreo.getText(), midni, txtpassword.getText());
                    ListaUsuarios.milista.añadir(usuario); //Aáde el usuario a la lista de usuarios
                    JOptionPane.showMessageDialog(null, "Creación admitida:\n"
                        + "Usuario creado correctamente.", "Información",
                        JOptionPane.INFORMATION_MESSAGE); 
                    limpiarceldas(); //pone los campos en blanco
                    this.dispose(); //Cierra esta ventana
                    Vprincipal.inicio.setVisible(true); //Hace visible la ventana principal
                } else { //Si hay algún campo vacio salta un mensaje
                    JOptionPane.showMessageDialog(null, "Creación denegada:\n"
                            + "Error. Hay algún campo vacio", "Error",
                            JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch (EmailCorrectoException e) {
            JOptionPane.showMessageDialog(null, "Creación denegada:\n"
                    + e.getMessage(), "Error",
                    JOptionPane.ERROR_MESSAGE);
        } catch (ContrasenhaCorrectaException e) {
            JOptionPane.showMessageDialog(null, "Creación denegada:\n"
                    + e.getMessage(), "Error",
                    JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Creación denegada:\n"
                    + e.getMessage(), "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonEnviarActionPerformed

    private void txtcorreo2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcorreo2FocusLost
        //Si los correos no coinciden pone el siguiente mensaje en un label
        if (!txtcorreo.getText().equalsIgnoreCase(txtcorreo2.getText())) {
            mensajeCorreo.setText("Los correos no coinciden!");
        }
    }//GEN-LAST:event_txtcorreo2FocusLost

    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
        limpiarceldas(); //Borra los campos de registro
    }//GEN-LAST:event_botonBorrarActionPerformed

    /**
     * Método para cambiar el icono de la ventana
     * @return
     */
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("imagenes/iconoPastilla.png"));

        return retValue;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vregistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vregistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vregistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vregistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                registro.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonEnviar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLogoAddUser;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblapellidos;
    private javax.swing.JLabel lblcorreo;
    private javax.swing.JLabel lblcorreo2;
    private javax.swing.JLabel lbldni;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lblnombreUsuario;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JLabel lblpassword2;
    private javax.swing.JLabel mensajeCorreo;
    private javax.swing.JTextField txtapellidos;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtcorreo2;
    private javax.swing.JTextField txtdni;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JPasswordField txtpassword2;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
    /**
     * Método para borrar los campos
     */
    private void limpiarceldas() {
        txtusuario.setText("");
        txtnombre.setText("");
        txtapellidos.setText("");
        txtdni.setText("");
        txtcorreo.setText("");
        txtcorreo2.setText("");
        txtpassword.setText("");
        txtpassword2.setText("");
    }
}
